# .github/workflows/docker-ghcr.yml
name: Build & Push (Production)

on:
  push:
    branches: ["main"]

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/whatsapp:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ env.IMAGE }}
